kind: pipline
name: default

steps:
- name: build
  image: insready/bazel
  commands:
    - apt-get update && apt-get install patch -y
    - bazel build //...
    # - cd examples/grpc_clients/java_client && bazel build //...
    # - cd examples/grpc_clients/ruby_client && bazel build //...
    # - cd examples/grpc_clients/rust_client && bazel build //...
    # - cd examples/grpc_clients/python_asyncio_client && bazel build //...
