on: push
name: Check
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build all
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //...
    - name: test all
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //...
