on:
  push:
    branches:
      - release

name: Release
jobs:
  checks:
    name: run
    runs-on: self-hosted
    services:
      consul:
        image: consul:latest
        ports:
          - 8500
      zookeeper:
        image: zookeeper:latest
        ports:
          - 2181
      etcd:
        image: quay.io/coreos/etcd:latest
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 2379
    steps:
    - name: test all
      uses: ngalaiko/bazel-action/1.2.1@master
      env:
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
      with:
        args: test //...

    - name: Release to GitHub
      uses: ngalaiko/bazel-action/1.2.1@master
      env:
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
      with:
        args: run //:deploy-github -- release